# 串行执行 jobs

name: Serial

on:
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - name: 执行 build1
        run: echo Hello, 1!

  build2:
    runs-on: ubuntu-latest
    # 只有 build1 成功后才会执行 build2
    if: ${{ success() }}
    needs: [build1]
    steps:
      - name: 执行 build2
        run: echo Hello, 2!
